version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    # dev
    command: gulp
    # prod
    # command: bash -c "npm install && node ./dist/index.js"
    

  # to start: docker-compose up


    # command: node ./dist/index.js
    # docker stop $(docker ps -a -q)
    # docker rm $(docker ps -a -q)
    # docker stop $(docker ps -aq)
    # docker rm $(docker ps -a -q)