// only use this if you need to store server ssh keys in github
node {
	stage('do something with git') {
	    // create ssh agent to allow jenkins to access server
		sshagent (credentials: ['github-key']) {
			// get last commid id from respository
			sh 'git ls-remote -h --refs git@github.com:JamesMillercus/Template.git master |awk "{print $1}"'
		}
	}
}